name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test-coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-pull-request
          path: coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-pull-request
          path: coverage
      - uses: actions/download-artifact@v4
        with:
          name: coverage-pull-request
          path: coverage-pull-request
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-pull-request/coverage-final.json
