name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test-coverage

      - name: Report test coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Frontend"
          json-summary-path: "./coverage/coverage-final-frontend.json"
          json-final-path: "./coverage/coverage-final-frontend.json"
